CREATE TABLE steam_game (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    is_released BOOLEAN NOT NULL,
    release_date TIMESTAMP,
    has_ai BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);